### PR TITLE
Fix "ready" state for viewer API

### LINKED ISSUE #164: `ready` promise is fulfilled before `viewer` API is available
The `ready` promise must only be fulfilled after everything, including OpenSeadragon, is fully instantiated.

See #163

### PR DESCRIPTION
**Pull request by t11r**
Add promise creator so every component can define ready conditions, use it in scan component so "ready" is only fulfilled after viewer has been initialized.

Resolves #164

### CODE REVIEW

File: src/components/ViewScan.vue [hunk 1]
```diff
@@ -387,6 +391,9 @@ export default {
 
 			this.$api.expose(this.resetScan);
 			this.$api.expose(this.viewer, 'viewer');
+
+			// TODO: How to reject?
```
Comment (ubbo) [inline src/components/ViewScan.vue]: create an issue?

**Review by ubbo — APPROVED** [review]
looks fine for me. possibly move the TODO to an issue

File: src/components/ViewScan.vue (hunk 1 above)
Comment (t11r) [reply src/components/ViewScan.vue]: Nah, that’s probably never gonna happen. I removed the comment 😇️
